### ISSUE TITLE
Windows 10 java 8 issue

### ISSUE THREAD

**Issue by xcier** [NotAlexNoyle/webos-quick-install#2]
Jan 26, 2022 2:46:39 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0xffffffff80000002. Windows RegCreateKeyEx(...) returned error code 5.
Jan 26, 2022 2:46:39 PM java.util.prefs.WindowsPreferences WindowsRegOpenKey1
WARNING: Trying to recreate Windows registry node Software\JavaSoft\Prefs at root 0xffffffff80000002.
Jan 26, 2022 2:46:39 PM java.util.prefs.WindowsPreferences openKey
WARNING: Could not open windows registry node Software\JavaSoft\Prefs at root 0xffffffff80000002. Windows RegOpenKey(...) returned error code 2.
Jan 26, 2022 2:46:40 PM java.util.prefs.WindowsPreferences WindowsRegOpenKey1
WARNING: Trying to recreate Windows registry node Software\JavaSoft\Prefs at root 0xffffffff80000002.
Jan 26, 2022 2:46:40 PM java.util.prefs.WindowsPreferences openKey
WARNING: Could not open windows registry node Software\JavaSoft\Prefs at root 0xffffffff80000002. Windows RegOpenKey(...) returned error code 2.
Jan 26, 2022 2:46:40 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using WebOSQuickInstallApp
Jan 26, 2022 2:46:40 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.vendorId using UnknownApplicationVendor

**Comment by codepoet80** [comment]
I'm having issues with WOSQI 4.7.2u on all platforms. Try 4.6.0, available here: http://www.webosarchive.com/docs/appstores/

**Comment by NotAlexNoyle** [comment]
> I'm having issues with WOSQI 4.7.2u on all platforms. Try 4.6.0, available here: http://www.webosarchive.com/docs/appstores/

Can you elaborate? I am back to working on WOSQI.

**Comment by codepoet80** [comment]
Excited that there's new work happening on this! I have been unable to get 4.7.2 working on any platform -- Linux, Windows and Mac. I'm fairly sure is a Java compat issue. Getting a version of Java that the rest of the SDK is happy with is a bit of a trick on Linux. I follow these instructions: https://www.fosstechnix.com/install-oracle-java-8-on-ubuntu-20-04/

On Mac, I've stopped upgrading at Mojave, and still use Apple Java installer: https://support.apple.com/kb/dl1572?locale=en_US

On Windows, I use both 10 and 11 and a newer version of Java. I'll get exact details and update here. All have the same symptoms with 4.7.2. Here's the command line output when running on Ubuntu 22.04 -- of note, the same ipk installed fine seconds later in 4.6.0

```
java -jar WebOS-Quick-Install-4-7-2.jar 
Nov 24, 2022 8:14:19 PM java.util.prefs.FileSystemPreferences$2 run
WARNING: Could not create system preferences directory. System preferences are unusable.
Nov 24, 2022 8:14:19 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /opt/jdk/jdk1.8.0_351/jre/.systemPrefs/prefs.xml
Nov 24, 2022 8:14:20 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/jonwise/.java/.userPrefs/prefs.xml
Nov 24, 2022 8:14:21 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using WebOSQuickInstallApp
Nov 24, 2022 8:14:51 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 0.
Nov 24, 2022 8:14:51 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
ERROR: Unable to copy file to install directory: /home/jonwise/Downloads/com.appbookshop.success_1.0.0_all.ipk
com.appbookshop.success_1.0.0_all.ipk (No such file or directory)
java.io.FileNotFoundException: com.appbookshop.success_1.0.0_all.ipk (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at ca.canuckcoding.novacom.NovacomCommand.writeFileToOutputStream(NovacomCommand.java:105)
	at ca.canuckcoding.novacom.NovacomCommand.run(NovacomCommand.java:62)
```

**Comment by NotAlexNoyle** [comment]
> Excited that there's new work happening on this! I have been unable to get 4.7.2 working on any platform -- Linux, Windows and Mac. I'm fairly sure is a Java compat issue. Getting a version of Java that the rest of the SDK is happy with is a bit of a trick on Linux. I follow these instructions: https://www.fosstechnix.com/install-oracle-java-8-on-ubuntu-20-04/
> 
> On Mac, I've stopped upgrading at Mojave, and still use Apple Java installer: https://support.apple.com/kb/dl1572?locale=en_US
> 
> On Windows, I use both 10 and 11 and a newer version of Java. I'll get exact details and update here. All have the same symptoms with 4.7.2. Here's the command line output when running on Ubuntu 22.04 -- of note, the same ipk installed fine seconds later in 4.6.0
> 
> ```
> java -jar WebOS-Quick-Install-4-7-2.jar 
> Nov 24, 2022 8:14:19 PM java.util.prefs.FileSystemPreferences$2 run
> WARNING: Could not create system preferences directory. System preferences are unusable.
> Nov 24, 2022 8:14:19 PM java.util.prefs.FileSystemPreferences$6 run
> WARNING: Prefs file removed in background /opt/jdk/jdk1.8.0_351/jre/.systemPrefs/prefs.xml
> Nov 24, 2022 8:14:20 PM java.util.prefs.FileSystemPreferences$6 run
> WARNING: Prefs file removed in background /home/jonwise/.java/.userPrefs/prefs.xml
> Nov 24, 2022 8:14:21 PM org.jdesktop.application.LocalStorage getId
> WARNING: unspecified resource Application.id using WebOSQuickInstallApp
> Nov 24, 2022 8:14:51 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
> WARNING: Could not lock System prefs. Unix error code 0.
> Nov 24, 2022 8:14:51 PM java.util.prefs.FileSystemPreferences syncWorld
> WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
> ERROR: Unable to copy file to install directory: /home/jonwise/Downloads/com.appbookshop.success_1.0.0_all.ipk
> com.appbookshop.success_1.0.0_all.ipk (No such file or directory)
> java.io.FileNotFoundException: com.appbookshop.success_1.0.0_all.ipk (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at ca.canuckcoding.novacom.NovacomCommand.writeFileToOutputStream(NovacomCommand.java:105)
> 	at ca.canuckcoding.novacom.NovacomCommand.run(NovacomCommand.java:62)
> ```

I think your issues are all caused by the fact that WOSQI builds against Java 12. I will revert to Java 8 (specifically the updated, secure JDK distribution by OpenLogic) for the release of WOSQI 4.8.0. That should fix your problems on Windows and Linux.

On your Mojave machine, I would *highly* recommend uninstalling apple’s Java 6 distribution. Not only is it full of vulnerabilities, my Java code uses Java 7 specific file APIs. I would suggest using jenv via homebrew to install OpenLogic’s JDK 8.

**Comment by NotAlexNoyle** [comment]
@codepoet80 please try this early build of 4.8.0 to see if it fixes your java runtime problems. It is HIGHLY incomplete, so please don't try to use it normally, I'm only uploading this so you can test the JREs.

https://trueog.net/WOSQI.jar

**Comment by codepoet80** [comment]
For completeness on 4.7.2, console output on Windows 11 running Java:
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

```
java -jar WebOS-Quick-Install-4-7-2.jar
Nov 25, 2022 9:47:04 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Nov 25, 2022 9:47:04 AM java.util.prefs.WindowsPreferences WindowsRegOpenKey1
WARNING: Trying to recreate Windows registry node Software\JavaSoft\Prefs at root 0x80000002.
Nov 25, 2022 9:47:04 AM java.util.prefs.WindowsPreferences openKey
WARNING: Could not open windows registry node Software\JavaSoft\Prefs at root 0x80000002. Windows RegOpenKey(...) returned error code 2.
Nov 25, 2022 9:47:12 AM java.util.prefs.WindowsPreferences WindowsRegOpenKey1
WARNING: Trying to recreate Windows registry node Software\JavaSoft\Prefs at root 0x80000002.
Nov 25, 2022 9:47:12 AM java.util.prefs.WindowsPreferences openKey
WARNING: Could not open windows registry node Software\JavaSoft\Prefs at root 0x80000002. Windows RegOpenKey(...) returned error code 2.
Nov 25, 2022 9:47:12 AM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using WebOSQuickInstallApp
Nov 25, 2022 9:47:12 AM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.vendorId using UnknownApplicationVendor
ERROR: Unable to copy file to install directory: C:\Users\jonwise\Downloads\com.forethoughtlabs.studentorganizer_2.0.4_all.ipk
com.forethoughtlabs.studentorganizer_2.0.4_all.ipk (The system cannot find the file specified)
java.io.FileNotFoundException: com.forethoughtlabs.studentorganizer_2.0.4_all.ipk (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at ca.canuckcoding.novacom.NovacomCommand.writeFileToOutputStream(NovacomCommand.java:105)
        at ca.canuckcoding.novacom.NovacomCommand.run(NovacomCommand.java:62)
```

**Comment by jwise-mfg** [comment]
Tried your 4.8.0 preview build in the same environment.
When starting, it claims there isn't a device present (nice improvement: it lets me continue!)
However, it shows my connected Touchpad in the drop-down -- but when I try to install an app, it again asserts there is no device present and won't install.
![NotSureIfDeviceIsConnected](https://user-images.githubusercontent.com/57234292/204009937-5076ce2e-1b87-4558-9fe9-820b627ce1d3.png)

**Comment by NotAlexNoyle** [comment]
> Tried your 4.8.0 preview build in the same environment. When starting, it claims there isn't a device present (nice improvement: it lets me continue!) However, it shows my connected Touchpad in the drop-down -- but when I try to install an app, it again asserts there is no device present and won't install. ![NotSureIfDeviceIsConnected](https://user-images.githubusercontent.com/57234292/204009937-5076ce2e-1b87-4558-9fe9-820b627ce1d3.png)

That's a consequence of a half-implemented dynamic device detection feature. I need to get the novacomd driver installer functionality working again on modern linux, and then I will be able to debug that part of the program again.

**Comment by codepoet80** [comment]
For Debian-based modern Linux, Herrie has it working:
https://github.com/Herrie82/palm-novacom

**Comment by NotAlexNoyle** [comment]
> For Debian-based modern Linux, Herrie has it working: https://github.com/Herrie82/palm-novacom

I've seen that, I don't love the implementation. It's not distro or init system agnostic. I am thinking of merging relevant parts of this: https://github.com/incidentist/novacomd and my raspberry pi fork: https://github.com/NotAlexNoyle/novacomd into one universal *nix novacomd installer. Supporting linux, the BSDs, macOS, etc.

**Comment by NotAlexNoyle** [comment]
The new *nix novacomd installer will be published here https://github.com/NotAlexNoyle/novacomd-bootstrap

I made it a separate project so that I could use a more permissive license. WOSQI 4.8.0 will bundle it into the .jar like a library.
